<a href="https://colab.research.google.com/github/Naruki-Ichihara/HowToUsePython/blob/main/1_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# How to use Numpy

## はじめに
numpyはpython上で動作する数値計算用モジュールです．numpyはデータを高密度のデータバッファへ格納し，さまざまな数値演算操作を行うインターフェイスを提供します．

## numpy配列の属性

In [4]:
import numpy as np
x = np.random.randint(10, size=(3, 4, 5))
x

array([[[4, 7, 5, 6, 0],
        [3, 3, 4, 9, 6],
        [0, 6, 6, 2, 5],
        [7, 9, 7, 0, 3]],

       [[0, 2, 8, 2, 2],
        [3, 5, 9, 6, 3],
        [4, 5, 0, 6, 3],
        [6, 3, 8, 2, 5]],

       [[4, 2, 5, 4, 0],
        [1, 3, 0, 9, 6],
        [1, 0, 8, 6, 5],
        [8, 4, 5, 4, 6]]])

In [ ]:
# 次元数
x.ndim

3

In [ ]:
# 各次元のサイズ
x.shape

(3, 4, 5)

In [ ]:
# 配列の合計サイズ
x.size

60

In [ ]:
# 配列のデータ型
# numpy配列の各要素はpythonリストとは異なり同一属性である必要があります．
x.dtype

dtype('int64')

## 配列のスライス
numpy配列の部分配列にアクセスします．これはpythonリストにおけるスライスと同様にコロン記号を利用します．
ただしnumpy配列のスライスはpythonリストと異なり，参照元のnumpy配列のビューを返します．すなわちスライスのポインタは元々のデータバッファをさしています．

これによりスライス，あるいは元のnumpy配列の要素が更新された場合，スライスあるいは元のnumpy配列いずれも値が更新されます．

In [3]:
x = np.arange(10)
x

NameError: ignored

In [ ]:
# 最初から4番目までの部分配列にアクセス <5
x[:5]

array([0, 1, 2, 3, 4])

In [ ]:
# ５番目以降の全ての要素にアクセス 5<=
x[5:]

array([5, 6, 7, 8, 9])

In [ ]:
# 5番目から8番目までの要素にアクセス 5<= <8
x[4:9]

array([4, 5, 6, 7, 8])

In [ ]:
# n個おきに要素を取り出す x[::n+1]
x[::2]

array([0, 2, 4, 6, 8])

In [ ]:
# indexがmからn個おきに取り出す x[m::n+1]
x[2::2]

array([2, 4, 6, 8])

In [ ]:
# 逆順に取り出す
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

### 配列のコピー
明治的に配列のコピーをする場合

```
copy()
```
メソッドを使用します．


In [ ]:
x_copy = x[::-1].copy()
x_copy

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

## 配列の形状変更
numpy一次元配列を二次元の行，あるいは列ベクトルに変換します．

In [ ]:
x = np.array([1, 2, 3])
x.shape

(3,)

In [ ]:
# 行ベクトルのビュー
x[np.newaxis, :].shape

(1, 3)

In [ ]:
# 列ベクトルのビュー
x[:, np.newaxis].shape

(3, 1)

## ユニバーサル関数によるベクトル化演算
多くのpythonコードにおいてループ処理はボトルネックになります．これはpythonが動的型付け言語であるためで，各イテレーションでの型チェックと関数の呼び出しがボトルネックとなります．numpyのufuncは，静的型付けでコンパイル済の関数に対するシンプルなインターフェイスを提供します．

## np.meshgrid

In [13]:
mat = np.random.rand(3, 3)
mat

array([[0.3527269 , 0.27125765, 0.86624186],
       [0.41884214, 0.27374909, 0.06387897],
       [0.72040411, 0.32998695, 0.6979809 ]])

In [20]:
row, columns = np.meshgrid(range(mat.shape[0]), range(mat.shape[1]), indexing='ij')
columns

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]])

In [10]:
mat.flatten()

array([0.70111178, 0.53850417, 0.75922419, 0.74661191, 0.97665519,
       0.70044992, 0.01900253, 0.00656709, 0.153724  ])